language: c
compiler:
    - gcc
    - clang
addons:
    apt:
        packages:
            - asciidoc
            - xmlto
script: "./autogen.sh && ./configure && make"
branches:
    only:
        - master
notifications:
    recipients:
        - wong.syrone@gmail.com
    email:
        on_success: change
        on_failure: always
